apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  
  replicas: 1

  template:
    metadata:
      labels:
        app: vpromc
        # this is the pod label
    spec:
      containers:
      - name: vpromc
        image: memcached
        ports:
        - name: vpromc-port
          containerPort: 11211

        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
