apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromq01
        # label of the pod
    spec:
      containers:
      - name: vpromq01
        image: rabbitmq
        ports:
        - name: vpromq01-port
          containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_PASS
        # this is the offical name of the env var from docker hub
          valueFrom:
            secretKeyRef:
              name: app-secret
              # this is from the app-secret.yaml
              key: rmq-pass
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
          # this is from the application.properties file
